### PR TITLE
Redesign UI and add new features

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Here is a checklist for this:
- [ ] New UI (in progress)
- [ ] Full-on launcher
- [ ] SpaceDock mod browsing & management
- [ ] Instances
- [x] Auto-installation of BepInEx
- [ ] Implement everything in the backend with Rust (see below)
- [ ] CKAN querying and mod management

Notes:
- Currently I'm using mocks in TypeScript to do some of the backend work, as I am doing a lot of dev on my school Chromebook when I finish my classwork.
- The above reason is why eruda is installed for web-only dev (does not get bundled for tauri).
- SpaceDock's API does not currently support finding dependencies, so that feature is unavailable. :(
- SpaceDock's API did not support game-specific API browsing, but as of KSP-SpaceDock/SpaceDock#466 it will, however this feature is not in the live release yet. It's in the alpha branch as of the time of writing. However, this will automagically be compatible with the current code, as the required parameters will already be set, just waiting for use.

### CODE REVIEW

**Comment by RedstoneWizard08** [comment]
@Rexicon226 @cheese3660 mind if I tag y'all in on this?

**Comment by Rexicon226** [comment]
u gud!!
insane progress :D

**Comment by RedstoneWizard08** [comment]
:)

**Comment by RedstoneWizard08** [comment]
Hey @Rexicon226 @cheese3660 I hope it's okay but I'm going to add support for managing KSP1 instances as well, so this can be an all-in-one thing. I'm going to try to integrate CKAN querying as well, as soon as I can figure out how. I think this might act as a nicer replacement for CKAN as well as a SpaceWarp installer and manager.

**Comment by RedstoneWizard08** [comment]
Also, yes or no?
```ts
// The expected size of KSP1's `steam_api64.dll` in bytes.
// This helps to make sure that the game is not pirated.
// File path: `[KSP1_ROOT]/KSP_x64_Data/Plugins/x86_64/steam_api64.dll`
// Information from: SteamDB, DepotDownloader, KSP1 Installed Files
export const KSP1_STEAM_API_SIZE = 249120;

// The expected size of KSP2's `steam_api64.dll` in bytes.
// This helps to make sure that the game is not pirated.
// File path: `[KSP2_ROOT]/KSP2_x64_Data/Plugins/x86_64/steam_api64.dll`
// Information from: SteamDB, DepotDownloader, KSP2 Installed Files
export const KSP2_STEAM_API_SIZE = 295336;
```

**Comment by RedstoneWizard08** [comment]
Closing in favor of separating the repo. Wormhole is kinda its own thing now.

**Pull request closed without merging**
